export const OFFSET = "OFFSET";
export const SEARCHCHARECTER = "SEARCHCHARECTER";
export const CHARECTERLIST = "CHARECTERLIST";
export const SAVEDCHARECTERLIST = "SAVEDCHARECTERLIST";
export const ADDORREMOVECHARECTER = "ADDORREMOVECHARECTER";





