export const OFFSET = "OFFSET";
export const SEARCHCHARECTER = "SEARCHCHARECTER";
export const ADDCHARECTER = "ADDCHARECTER";
export const REMOVECHARECTER = "REMOVECHARECTER";
export const CHARECTERLIST = "CHARECTERLIST";
export const SAVEDCHARECTERLIST = "SAVEDCHARECTERLIST";




